<?php
/**
 * CapacityplanningthresholdApi
 * PHP version 5
 *
 * @category Class
 * @package  BumbalClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bumbal Client Api
 *
 * Bumbal API documentation
 *
 * OpenAPI spec version: 2.0
 * Contact: support@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace BumbalClient\API;

use \BumbalClient\ApiClient;
use \BumbalClient\ApiException;
use \BumbalClient\Configuration;
use \BumbalClient\ObjectSerializer;

/**
 * CapacityplanningthresholdApi Class Doc Comment
 *
 * @category Class
 * @package  BumbalClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CapacityplanningthresholdApi
{
    /**
     * API Client
     *
     * @var \BumbalClient\ApiClient instance of the ApiClient
     */
    protected $apiClient;

    /**
     * Constructor
     *
     * @param \BumbalClient\ApiClient|null $apiClient The api client to use
     */
    public function __construct(?\BumbalClient\ApiClient $apiClient = null)
    {
        if ($apiClient === null) {
            $apiClient = new ApiClient();
        }

        $this->apiClient = $apiClient;
    }

    /**
     * Get API client
     *
     * @return \BumbalClient\ApiClient get the API client
     */
    public function getApiClient()
    {
        return $this->apiClient;
    }

    /**
     * Set the API client
     *
     * @param \BumbalClient\ApiClient $apiClient set the API client
     *
     * @return CapacityplanningthresholdApi
     */
    public function setApiClient(\BumbalClient\ApiClient $apiClient)
    {
        $this->apiClient = $apiClient;
        return $this;
    }

    /**
     * Operation deleteCapacityPlanningThreshold
     *
     * Delete a CapacityPlanningThreshold
     *
     * @param int $capacity_planning_threshold_id ID of CapacityPlanningThreshold to delete (required)
     * @throws \BumbalClient\ApiException on non-2xx response
     * @return \BumbalClient\Model\ApiResponse
     */
    public function deleteCapacityPlanningThreshold($capacity_planning_threshold_id)
    {
        list($response) = $this->deleteCapacityPlanningThresholdWithHttpInfo($capacity_planning_threshold_id);
        return $response;
    }

    /**
     * Operation deleteCapacityPlanningThresholdWithHttpInfo
     *
     * Delete a CapacityPlanningThreshold
     *
     * @param int $capacity_planning_threshold_id ID of CapacityPlanningThreshold to delete (required)
     * @throws \BumbalClient\ApiException on non-2xx response
     * @return array of \BumbalClient\Model\ApiResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteCapacityPlanningThresholdWithHttpInfo($capacity_planning_threshold_id)
    {
        // verify the required parameter 'capacity_planning_threshold_id' is set
        if ($capacity_planning_threshold_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $capacity_planning_threshold_id when calling deleteCapacityPlanningThreshold');
        }
        // parse inputs
        $resourcePath = "/capacity-planning-threshold/{capacityPlanningThresholdId}";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json', 'application/xml']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType([]);

        // path params
        if ($capacity_planning_threshold_id !== null) {
            $resourcePath = str_replace(
                "{" . "capacityPlanningThresholdId" . "}",
                $this->apiClient->getSerializer()->toPathValue($capacity_planning_threshold_id),
                $resourcePath
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('ApiKey');
        if (strlen($apiKey ?? '') !== 0) {
            $headerParams['ApiKey'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('Authorization');
        if (strlen($apiKey ?? '') !== 0) {
            $headerParams['Authorization'] = $apiKey;
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'DELETE',
                $queryParams,
                $httpBody,
                $headerParams,
                '\BumbalClient\Model\ApiResponse',
                '/capacity-planning-threshold/{capacityPlanningThresholdId}'
            );

            return [$this->apiClient->getSerializer()->deserialize($response, '\BumbalClient\Model\ApiResponse', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\BumbalClient\Model\ApiResponse', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation retrieveCapacityPlanningThreshold
     *
     * Find CapacityPlanningThreshold by ID
     *
     * @param int $capacity_planning_threshold_id ID of CapacityPlanningThreshold to return (required)
     * @throws \BumbalClient\ApiException on non-2xx response
     * @return \BumbalClient\Model\CapacityPlanningThreshold
     */
    public function retrieveCapacityPlanningThreshold($capacity_planning_threshold_id)
    {
        list($response) = $this->retrieveCapacityPlanningThresholdWithHttpInfo($capacity_planning_threshold_id);
        return $response;
    }

    /**
     * Operation retrieveCapacityPlanningThresholdWithHttpInfo
     *
     * Find CapacityPlanningThreshold by ID
     *
     * @param int $capacity_planning_threshold_id ID of CapacityPlanningThreshold to return (required)
     * @throws \BumbalClient\ApiException on non-2xx response
     * @return array of \BumbalClient\Model\CapacityPlanningThreshold, HTTP status code, HTTP response headers (array of strings)
     */
    public function retrieveCapacityPlanningThresholdWithHttpInfo($capacity_planning_threshold_id)
    {
        // verify the required parameter 'capacity_planning_threshold_id' is set
        if ($capacity_planning_threshold_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $capacity_planning_threshold_id when calling retrieveCapacityPlanningThreshold');
        }
        // parse inputs
        $resourcePath = "/capacity-planning-threshold/{capacityPlanningThresholdId}";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json', 'application/xml']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType([]);

        // path params
        if ($capacity_planning_threshold_id !== null) {
            $resourcePath = str_replace(
                "{" . "capacityPlanningThresholdId" . "}",
                $this->apiClient->getSerializer()->toPathValue($capacity_planning_threshold_id),
                $resourcePath
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('ApiKey');
        if (strlen($apiKey ?? '') !== 0) {
            $headerParams['ApiKey'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('Authorization');
        if (strlen($apiKey ?? '') !== 0) {
            $headerParams['Authorization'] = $apiKey;
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'GET',
                $queryParams,
                $httpBody,
                $headerParams,
                '\BumbalClient\Model\CapacityPlanningThreshold',
                '/capacity-planning-threshold/{capacityPlanningThresholdId}'
            );

            return [$this->apiClient->getSerializer()->deserialize($response, '\BumbalClient\Model\CapacityPlanningThreshold', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\BumbalClient\Model\CapacityPlanningThreshold', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation retrieveListCapacityPlanningThreshold
     *
     * Retrieve List of CapacityPlanningThresholds
     *
     * @param \BumbalClient\Model\CapacityPlanningThresholdRetrieveListArguments $arguments  (required)
     * @throws \BumbalClient\ApiException on non-2xx response
     * @return \BumbalClient\Model\CapacityPlanningThreshold
     */
    public function retrieveListCapacityPlanningThreshold($arguments)
    {
        list($response) = $this->retrieveListCapacityPlanningThresholdWithHttpInfo($arguments);
        return $response;
    }

    /**
     * Operation retrieveListCapacityPlanningThresholdWithHttpInfo
     *
     * Retrieve List of CapacityPlanningThresholds
     *
     * @param \BumbalClient\Model\CapacityPlanningThresholdRetrieveListArguments $arguments  (required)
     * @throws \BumbalClient\ApiException on non-2xx response
     * @return array of \BumbalClient\Model\CapacityPlanningThreshold, HTTP status code, HTTP response headers (array of strings)
     */
    public function retrieveListCapacityPlanningThresholdWithHttpInfo($arguments)
    {
        // verify the required parameter 'arguments' is set
        if ($arguments === null) {
            throw new \InvalidArgumentException('Missing the required parameter $arguments when calling retrieveListCapacityPlanningThreshold');
        }
        // parse inputs
        $resourcePath = "/capacity-planning-threshold";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json', 'application/xml']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json', 'application/xml']);

        // body params
        $_tempBody = null;
        if (isset($arguments)) {
            $_tempBody = $arguments;
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('ApiKey');
        if (strlen($apiKey ?? '') !== 0) {
            $headerParams['ApiKey'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('Authorization');
        if (strlen($apiKey ?? '') !== 0) {
            $headerParams['Authorization'] = $apiKey;
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'PUT',
                $queryParams,
                $httpBody,
                $headerParams,
                '\BumbalClient\Model\CapacityPlanningThreshold',
                '/capacity-planning-threshold'
            );

            return [$this->apiClient->getSerializer()->deserialize($response, '\BumbalClient\Model\CapacityPlanningThreshold', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\BumbalClient\Model\CapacityPlanningThreshold', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation setCapacityPlanningThreshold
     *
     * Set (create or update) a CapacityPlanningThreshold
     *
     * @param \BumbalClient\Model\CapacityPlanningThreshold $body  (required)
     * @throws \BumbalClient\ApiException on non-2xx response
     * @return \BumbalClient\Model\ApiResponse
     */
    public function setCapacityPlanningThreshold($body)
    {
        list($response) = $this->setCapacityPlanningThresholdWithHttpInfo($body);
        return $response;
    }

    /**
     * Operation setCapacityPlanningThresholdWithHttpInfo
     *
     * Set (create or update) a CapacityPlanningThreshold
     *
     * @param \BumbalClient\Model\CapacityPlanningThreshold $body  (required)
     * @throws \BumbalClient\ApiException on non-2xx response
     * @return array of \BumbalClient\Model\ApiResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function setCapacityPlanningThresholdWithHttpInfo($body)
    {
        // verify the required parameter 'body' is set
        if ($body === null) {
            throw new \InvalidArgumentException('Missing the required parameter $body when calling setCapacityPlanningThreshold');
        }
        // parse inputs
        $resourcePath = "/capacity-planning-threshold/set";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json', 'application/xml']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json', 'application/xml']);

        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('ApiKey');
        if (strlen($apiKey ?? '') !== 0) {
            $headerParams['ApiKey'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('Authorization');
        if (strlen($apiKey ?? '') !== 0) {
            $headerParams['Authorization'] = $apiKey;
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'POST',
                $queryParams,
                $httpBody,
                $headerParams,
                '\BumbalClient\Model\ApiResponse',
                '/capacity-planning-threshold/set'
            );

            return [$this->apiClient->getSerializer()->deserialize($response, '\BumbalClient\Model\ApiResponse', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\BumbalClient\Model\ApiResponse', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }
}
