<?php
/**
 * BrandCommunicationSettingsModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  BumbalClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bumbal Client Api
 *
 * Bumbal API documentation
 *
 * OpenAPI spec version: 2.0
 * Contact: support@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.44
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace BumbalClient;

/**
 * BrandCommunicationSettingsModelTest Class Doc Comment
 *
 * @category    Class
 * @description BrandCommunicationSettingsModel
 * @package     BumbalClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BrandCommunicationSettingsModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "BrandCommunicationSettingsModel"
     */
    public function testBrandCommunicationSettingsModel()
    {
    }

    /**
     * Test attribute "sender_phone_number"
     */
    public function testPropertySenderPhoneNumber()
    {
    }

    /**
     * Test attribute "email_sender_address"
     */
    public function testPropertyEmailSenderAddress()
    {
    }

    /**
     * Test attribute "mailgun_domain"
     */
    public function testPropertyMailgunDomain()
    {
    }

    /**
     * Test attribute "mailgun_domain_region"
     */
    public function testPropertyMailgunDomainRegion()
    {
    }

    /**
     * Test attribute "mailgun_api_key"
     */
    public function testPropertyMailgunApiKey()
    {
    }

    /**
     * Test attribute "spryng_company"
     */
    public function testPropertySpryngCompany()
    {
    }

    /**
     * Test attribute "spryng_api_key"
     */
    public function testPropertySpryngApiKey()
    {
    }
}
