<?php
/**
 * CommunicationMappingOptionsModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  BumbalClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bumbal Client Api
 *
 * Bumbal API documentation
 *
 * OpenAPI spec version: 2.0
 * Contact: info@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace BumbalClient;

/**
 * CommunicationMappingOptionsModelTest Class Doc Comment
 *
 * @category    Class */
// * @description CommunicationMappingOptionsModel
/**
 * @package     BumbalClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CommunicationMappingOptionsModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CommunicationMappingOptionsModel"
     */
    public function testCommunicationMappingOptionsModel()
    {
    }

    /**
     * Test attribute "include_template_name"
     */
    public function testPropertyIncludeTemplateName()
    {
    }

    /**
     * Test attribute "include_template_object"
     */
    public function testPropertyIncludeTemplateObject()
    {
    }

    /**
     * Test attribute "include_tags"
     */
    public function testPropertyIncludeTags()
    {
    }

    /**
     * Test attribute "include_tag_names"
     */
    public function testPropertyIncludeTagNames()
    {
    }

    /**
     * Test attribute "include_zones"
     */
    public function testPropertyIncludeZones()
    {
    }

    /**
     * Test attribute "include_zone_names"
     */
    public function testPropertyIncludeZoneNames()
    {
    }
}
