<?php
/**
 * CommunicationMappingFiltersModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  BumbalClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bumbal Client Api
 *
 * Bumbal API documentation
 *
 * OpenAPI spec version: 2.0
 * Contact: info@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace BumbalClient;

/**
 * CommunicationMappingFiltersModelTest Class Doc Comment
 *
 * @category    Class */
// * @description CommunicationMappingFiltersModel
/**
 * @package     BumbalClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CommunicationMappingFiltersModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CommunicationMappingFiltersModel"
     */
    public function testCommunicationMappingFiltersModel()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "updated_at_since"
     */
    public function testPropertyUpdatedAtSince()
    {
    }

    /**
     * Test attribute "tag_names"
     */
    public function testPropertyTagNames()
    {
    }

    /**
     * Test attribute "message_type_id"
     */
    public function testPropertyMessageTypeId()
    {
    }

    /**
     * Test attribute "message_type_names"
     */
    public function testPropertyMessageTypeNames()
    {
    }
}
