<?php
/**
 * ServiceWindowsSchemeFiltersModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  BumbalClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bumbal Client Api
 *
 * Bumbal API documentation
 *
 * OpenAPI spec version: 2.0
 * Contact: info@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace BumbalClient;

/**
 * ServiceWindowsSchemeFiltersModelTest Class Doc Comment
 *
 * @category    Class */
// * @description ServiceWindowsSchemeFiltersModel
/**
 * @package     BumbalClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ServiceWindowsSchemeFiltersModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ServiceWindowsSchemeFiltersModel"
     */
    public function testServiceWindowsSchemeFiltersModel()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "tag_names"
     */
    public function testPropertyTagNames()
    {
    }

    /**
     * Test attribute "tag_ids"
     */
    public function testPropertyTagIds()
    {
    }

    /**
     * Test attribute "zone_names"
     */
    public function testPropertyZoneNames()
    {
    }

    /**
     * Test attribute "zone_ids"
     */
    public function testPropertyZoneIds()
    {
    }

    /**
     * Test attribute "brand_names"
     */
    public function testPropertyBrandNames()
    {
    }

    /**
     * Test attribute "brand_ids"
     */
    public function testPropertyBrandIds()
    {
    }
}
