<?php
/**
 * CommunicationtemplateApiTest
 * PHP version 5
 *
 * @category Class
 * @package  BumbalClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bumbal Client Api
 *
 * Bumbal API documentation
 *
 * OpenAPI spec version: 2.0
 * Contact: info@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace BumbalClient;

use \BumbalClient\Configuration;
use \BumbalClient\ApiClient;
use \BumbalClient\ApiException;
use \BumbalClient\ObjectSerializer;

/**
 * CommunicationtemplateApiTest Class Doc Comment
 *
 * @category Class
 * @package  BumbalClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CommunicationtemplateApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createCommunicationTemplate
     *
     * Create a Communication Template.
     *
     */
    public function testCreateCommunicationTemplate()
    {
    }

    /**
     * Test case for deleteCommunicationTemplate
     *
     * Delete a communicationtemplate.
     *
     */
    public function testDeleteCommunicationTemplate()
    {
    }

    /**
     * Test case for retrieveCommunicationTemplate
     *
     * Retrieve a communicationtemplate.
     *
     */
    public function testRetrieveCommunicationTemplate()
    {
    }

    /**
     * Test case for retrieveListTemplate
     *
     * Retrieve List of Templates.
     *
     */
    public function testRetrieveListTemplate()
    {
    }
}
