<?php
/**
 * QuestionnaireTemplateQuestionOptionTextApiTest
 * PHP version 5
 *
 * @category Class
 * @package  BumbalClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bumbal Client Api
 *
 * Bumbal API documentation
 *
 * OpenAPI spec version: 2.0
 * Contact: support@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.44
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace BumbalClient;

use \BumbalClient\Configuration;
use \BumbalClient\ApiException;
use \BumbalClient\ObjectSerializer;

/**
 * QuestionnaireTemplateQuestionOptionTextApiTest Class Doc Comment
 *
 * @category Class
 * @package  BumbalClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class QuestionnaireTemplateQuestionOptionTextApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createQuestionnaireTemplateQuestionOptionText
     *
     * Add a new QuestionnaireTemplateQuestionOptionText.
     *
     */
    public function testCreateQuestionnaireTemplateQuestionOptionText()
    {
    }

    /**
     * Test case for deleteQuestionnaireTemplateQuestionOptionText
     *
     * Delete an QuestionnaireTemplateQuestionOptionText entry.
     *
     */
    public function testDeleteQuestionnaireTemplateQuestionOptionText()
    {
    }

    /**
     * Test case for retrieveListQuestionnaireTemplateQuestionOptionText
     *
     * Retrieve List of QuestionnaireTemplateQuestionOptionText.
     *
     */
    public function testRetrieveListQuestionnaireTemplateQuestionOptionText()
    {
    }

    /**
     * Test case for retrieveQuestionnaireTemplateQuestionOptionText
     *
     * Retrieve a QuestionnaireTemplateQuestionOptionText.
     *
     */
    public function testRetrieveQuestionnaireTemplateQuestionOptionText()
    {
    }

    /**
     * Test case for setQuestionnaireTemplateQuestionOptionText
     *
     * Set (create or update) a QuestionnaireTemplateQuestionOptionText.
     *
     */
    public function testSetQuestionnaireTemplateQuestionOptionText()
    {
    }

    /**
     * Test case for updateQuestionnaireTemplateQuestionOptionText
     *
     * Update a specific QuestionnaireTemplateQuestionOptionText object.
     *
     */
    public function testUpdateQuestionnaireTemplateQuestionOptionText()
    {
    }
}
